name: Workflow Commands
on: [push]

jobs:
    testing-workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting error message with params
              run: echo "::error title::Error Title,file=app.js,line=2::Missing semicolon"
            - name: Setting debug message with params
              run: echo "::debug title::Debug Title,file=app.js,line=2::Missing semicolon"
            - name: Setting warning message with params
              run: echo "::warning title::Warning Title,file=app.js,line=2::Missing semicolon"